version: '3'
services:
  front:
    container_name: front
    build:
      context: ./front/
      dockerfile: ./Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./front/:/app
      - .env:/app/.env
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: front_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front
  api:
    container_name: api
    build:
      context: ./back/
      dockerfile: ./Dockerfile
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./back/:/app
      - .env:/app/.env
    env_file:
      - ./.env

  db:
    image: mysql:8.0
    env_file:
    - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./back/mysql/conf.d:/etc/mysql/conf.d
      - ./back/migrations:/docker-entrypoint-initdb.d/migrations:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+09:00'

volumes:
  db_data:
